-- Create learner_progress table to track student progress on interactive content
CREATE TABLE IF NOT EXISTS learner_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    content_id BIGINT REFERENCES lesson_content(content_id) ON DELETE CASCADE,
    progress_percentage INTEGER DEFAULT 0,
    viewed_pages INTEGER[] DEFAULT '{}',
    last_page_index INTEGER DEFAULT 0,
    data JSONB DEFAULT '{}'::jsonb, -- For storing extra data like quiz scores, answers, etc.
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, content_id)
);

-- Enable RLS
ALTER TABLE learner_progress ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can view their own progress"
    ON learner_progress FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own progress"
    ON learner_progress FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own progress"
    ON learner_progress FOR UPDATE
    USING (auth.uid() = user_id);

-- Teachers can view progress of students in their classes (simplified for now, can be expanded)
CREATE POLICY "Teachers can view student progress"
    ON learner_progress FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM users
            WHERE users.id = auth.uid()
            AND users.role = 'instructor'
        )
    );
