export const ROLES = {
    ADMIN: 'ADMIN',
    SCHOOL_ADMIN: 'SCHOOL_ADMIN',
    INSTRUCTOR: 'INSTRUCTOR',
    TEACHER: 'TEACHER', // Alias for INSTRUCTOR
    STUDENT: 'STUDENT',
    PARENT: 'PARENT',
    CURRICULUM_DESIGNER: 'CURRICULUM_DESIGNER',
    SUPER_ADMIN: 'SUPER_ADMIN'
};

export const INSTITUTION_TYPES = {
    SECONDARY_SCHOOL: 'SECONDARY_SCHOOL',
    PRIMARY_SCHOOL: 'PRIMARY_SCHOOL',
    TERTIARY_INSTITUTION: 'TERTIARY_INSTITUTION',
    MINISTRY_OF_EDUCATION: 'MINISTRY_OF_EDUCATION',
    OTHER: 'OTHER'
};

export const INSTITUTION_TYPE_LABELS = {
    SECONDARY_SCHOOL: 'Secondary School',
    PRIMARY_SCHOOL: 'Primary School',
    TERTIARY_INSTITUTION: 'Tertiary Institution',
    MINISTRY_OF_EDUCATION: 'Ministry of Education',
    OTHER: 'Other'
};
