export const ROLES = {
    ADMIN: 'ADMIN',
    SCHOOL_ADMIN: 'SCHOOL_ADMIN',
    INSTRUCTOR: 'INSTRUCTOR',
    TEACHER: 'TEACHER', // Alias for INSTRUCTOR
    STUDENT: 'STUDENT',
    PARENT: 'PARENT',
    CURRICULUM_DESIGNER: 'CURRICULUM_DESIGNER',
    SUPER_ADMIN: 'SUPER_ADMIN'
};

export const INSTITUTION_TYPES = {
    UNIVERSITY: 'UNIVERSITY',
    COLLEGE: 'COLLEGE',
    SECONDARY_SCHOOL: 'SECONDARY SCHOOL',
    PRIMARY_SCHOOL: 'PRIMARY SCHOOL',
    INSTITUTE: 'INSTITUTE'
};
